seed : 42 # 101
debug : False
exp_name : '2.5D'
comment : 'unext-resnext101_32x4d-512'
# architecture
model_name : 'UNeXt'
backbone : 'swsl_resnext101_32x4d'
batch_size    : 32 # 64
img_size      : [512, 512]
positive_only : False
hard_arg      : True
normalize     : 'imagenet'
epochs        : 50 # 15
lr            : 0.0001 # 0.002
scheduler     : 'CosineAnnealingLR'
min_lr        : 0.0000001
T_0           : 25
warmup_epochs : 3
wd            : 0.000001
n_accumulate  : 1
n_fold        : 5
folds         : [0,1,2,3,4]
num_classes   : 3
device        : "cuda:0"
data_root     : '../data/images_512_512_resize_1_3_near/*' # '/tmp/images/*' # 
full_train    : False
center        : False
kimin_model   : True